server:
  port: ${USER_SERVICE_PORT}

spring:
  config:
    import: optional:file:../.env[.properties]
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}?authSource=admin
      auto-index-creation: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/

jwt:
  private-key: ${JWT_PRIVATE_KEY_PATH}
  expiration: ${JWT_EXPIRATION}
