server:
  port: ${GATEWAY_PORT}

spring:
  config:
    import: optional:file:../.env[.properties]
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/

jwt:
  public-key: ${JWT_PUBLIC_KEY_PATH}

internal:
  gateway-key: ${GATEWAY_INTERNAL_KEY}
