server:
  port: ${GATEWAY_PORT}
  ssl:
    enabled: ${GATEWAY_SSL_ENABLED:false}
    key-store: ${GATEWAY_SSL_KEY_STORE:}
    key-store-password: ${GATEWAY_SSL_KEY_STORE_PASSWORD:}
    key-store-type: ${GATEWAY_SSL_KEY_STORE_TYPE:PKCS12}

spring:
  config:
    import: optional:file:../../.env.local[.properties]
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: file:${JWT_PUBLIC_KEY_PATH}
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
          routes:
            - id: media-objects
              uri: ${MINIO_ENDPOINT}
              predicates:
                - Path=/ecom-media/**
                - Method=GET,HEAD
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/auth/**,/users/**
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/products/**
            - id: media-service
              uri: lb://MEDIA-SERVICE
              predicates:
                - Path=/media/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/
