server:
  port: ${MEDIA_SERVICE_PORT}

spring:
  config:
    import: optional:file:../.env[.properties]
  application:
    name: media-service
  mongodb:
    uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_MEDIA_DATABASE}?authSource=admin
    auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST}:${EUREKA_PORT}/eureka/

media:
  minio:
    endpoint: ${MINIO_ENDPOINT}
    access-key: ${MINIO_ACCESS_KEY}
    secret-key: ${MINIO_SECRET_KEY}
    bucket: ${MINIO_BUCKET}
  public-base-url: ${MEDIA_PUBLIC_BASE_URL}
  max-file-size-bytes: 2097152
