server:
  port: ${EUREKA_PORT:8761}

spring:
  application:
    name: discovery-server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  server:
    # In Dev: Set false so if you kill a service, it disappears instantly.
    enable-self-preservation: false
    
    # How often (in ms) the server scans for dead services to remove them.
    eviction-interval-timer-in-ms: 5000